name: ci-dotfiles

# Doc: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    tags:
      - "*"
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-dotfiles:
    runs-on: ubuntu-latest

    steps:
      # Doc: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      - name: Install deps, make & lint
        run: |
          apt update && apt install -y bash git make shellcheck vim
          make dotfiles vim
        # shellcheck ~/.bashrc
        # shellcheck ~/.bash_profile
